### ISSUE TITLE
开源

### ISSUE THREAD

**Issue by 77loggedaloha** [c-yn/ChaIR#2]
请问什么时候开源代码和预训练模型呢

**Comment by c-yn** [comment]
已经开源

**Comment by 77loggedaloha** [comment]
您的工作做的太好了，我是一个研二硕士生，期望能和您保持沟通与交流，我看您的工作里面，都涉及了频率域和自注意力的替代，我对这些概念并没有一个明确的理解，或者说我现在对low-level领域具体存在的问题还没有很明确，不知道能不能交流一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "c-yn/ChaIR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月13日(星期一) 凌晨4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [c-yn/ChaIR] 开源 (Issue #2)





 
已经开源

**Comment by c-yn** [comment]
好的，欢迎

**Comment by 77loggedaloha** [comment]
可以留一个email吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "c-yn/ChaIR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月13日(星期一) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [c-yn/ChaIR] 开源 (Issue #2)





 
好的，欢迎

**Comment by c-yn** [comment]
yuning.cui@in.tum.de
