### ISSUE TITLE
关于复现

### ISSUE THREAD

**Issue by fangxinGod** [c-yn/ChaIR#5]
老师您好，这里面的数据集地址该怎么填写呢，根据您提供的here里面的链接下载下来之后怎么进一步复现呢？

**Comment by c-yn** [comment]
按照dehazing子文件夹底部的文件夹组织方式放置数据集就可以了

**Comment by fangxinGod** [comment]
您好老师，有没有第二个数据集的网盘链接呀

**Comment by c-yn** [comment]
是OTS吗？ 我附的有gdrive的链接。官方下载的地址是：https://sites.google.com/view/reside-dehaze-datasets/reside-v0

**Comment by fangxinGod** [comment]
好的，谢谢老师的解答







---- 回复的原邮件 ----
| 发件人 | Yuning ***@***.***> |
| 发送日期 | 2024年3月25日 18:18 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [c-yn/ChaIR] 关于复现 (Issue #5) |

是OTS吗？ 我附的有gdrive的链接。官方下载的地址是：https://sites.google.com/view/reside-dehaze-datasets/reside-v0
